mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('taskmanager/', include('taskmanager.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #ex: /polls/
    path('', views.index, name='index'),
    # ex : /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex : /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex : /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

taskmanager/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'taskmanager'
urlpatterns = [
    #ex: /taskmanager/
    path('', views.index, name='index'),

    path('login/', auth_views.LoginView.as_view( template_name = 'taskmanager/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    # ex : /taskmanager/5/
    path('<int:task_id>/', views.detail, name='detail'),
    # ex: /taskmanager/completed_tasks
    path('completed_tasks/', views.completed_task_list, name='completed_tasks'),
    # /taskmanager/create
    path('create/',views.create, name='create'),
    # /taskmanager/5/edit
    path('<int:task_id>/edit/',views.edit, name='edit'),
    # /taskmanager/5/delete
    path('<int:task_id>/delete/',views.delete, name='delete'),
    # /taskmanager/5/toggle_status
    path('<int:task_id>/toggle_status/',views.toggle_status, name='toggle_status'),
]

taskmanager/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Task(models.Model):
    assignee = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name='assignee')
    creator = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    task_title = models.CharField(max_length=200)
    description = models.CharField(null=True, max_length=5000)
    status = models.BooleanField(default=False)
    created = models.DateTimeField('date created', null=True)
    finished = models.DateTimeField('date finished', null=True)
    modified = models.DateTimeField('date modified', null=True)

taskmanager/forms.py
from django import forms
from django.forms import ModelForm
from .models import Task
from django.contrib.auth.models import User

class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ['task_title', 'description']

class UserForm(ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    confirm_password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'password': forms.PasswordInput(),
            'confirm_password': forms.PasswordInput(),
        }

taskmanager/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

from .models import Task
from .forms import TaskForm, UserForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('taskmanager:index'))

def register(request):
    error_message = None
    if(request.method == 'POST'):
        form = UserForm(request.POST)
        if form.is_valid() and form.cleaned_data['password'] == form.cleaned_data['confirm_password']:
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            return HttpResponseRedirect(reverse('taskmanager:index'))
        elif form.cleaned_data['password'] != form.cleaned_data['confirm_password']:
            error_message = 'Passwords do not match!'
    else:
        form = UserForm()

    return render(request, 'taskmanager/register.html', {'form':form, 'error_message':error_message})

@login_required(login_url="login/")
def index(request):
    user = request.user
    latest_task_list = Task.objects.filter(assignee=user, status=False).order_by('-created')
    context = {'latest_task_list':latest_task_list}
    return render(request, 'taskmanager/index.html', context)

@login_required(login_url="login/")
def completed_task_list(request):
    user = request.user
    completed_task_list = Task.objects.filter(assignee=user, status=True).order_by('-finished')
    context = {'task_list':completed_task_list}
    return render(request, 'taskmanager/task_list.html', context)

@login_required(login_url="login/")
def create(request):
    user = request.user
    if(request.method == 'POST'):
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save(commit=False)
            task.status = False
            task.assignee = user
            task.creator = user
            task.created = timezone.now()
            task.modified = timezone.now()
            task.save()
            return HttpResponseRedirect(reverse('taskmanager:detail', args=(task.id,)))
    else:
        form = TaskForm()

    return render(request, 'taskmanager/create_task.html', {'taskform':form})

@login_required(login_url="login/")
def edit(request, task_id):
    user = request.user
    if(request.method == 'POST'):
        form = TaskForm(request.POST)
        if form.is_valid():
            try:
                task = Task.objects.filter(assignee=user).get(pk=task_id)
            except Task.DoesNotExist:
                return render(request, 'taskmanager/edit_task.html', {'error_message':'Task does not exist'})
            else:
                task.task_title = form.cleaned_data['task_title']
                task.description = form.cleaned_data['description']
                task.modified = timezone.now()
                task.save()
                return HttpResponseRedirect(reverse('taskmanager:detail', args=(task.id,)))
    else:
        try:
            task = get_object_or_404(Task, pk=task_id)
        except(KeyError, Task.DoesNotExist):
            return render(request, 'taskmanager/edit_task.html', {'error_message':'Task does not exist'})
        else:
            form = TaskForm(instance=task)
            return render(request, 'taskmanager/edit_task.html', {'task':task, 'form': form})

@login_required(login_url="login/")
def delete(request, task_id):
    if(request.method == 'POST'):
        try:
            task = get_object_or_404(Task, pk=task_id)
        except(KeyError, Task.DoesNotExist):
            return render(request, 'taskmanager/delete.html', {'error_message':'Task does not exist'})
        else:
            task.delete()
            latest_task_list = Task.objects.order_by('-created')
            context = {'latest_task_list':latest_task_list}
            return render(request, 'taskmanager/index.html', context)
    else:
        return render(request, 'taskmanager/delete.html', {'error_message':'Get request not allowed!'})

@login_required(login_url="login/")
def detail(request, task_id):
    user = request.user
    try:
        task = Task.objects.filter(assignee=user).get(pk=task_id)
    except Task.DoesNotExist:
        raise Http404("Task does not exist OR you are unauthorized to see this task.")
    return render(request, 'taskmanager/detail.html', {'task':task})

@login_required(login_url="login/")
def toggle_status(request, task_id):
    user = request.user
    try:
        task = Task.objects.filter(assignee=user).get(pk=task_id)
    except task.DoesNotExist:
        raise Http404("Task does not exist.")
    else:
        task.status = not task.status
        if task.status == True:
            task.finished = timezone.now()
        task.save()
    return HttpResponseRedirect(reverse('taskmanager:detail', args=(task.id,)))

taskmanager/templates/taskmanager/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>My Site</title>
    </head>

    <body>
    <h1> <a href="{% url 'taskmanager:index' %}" style="text-decoration:none"> {% block appname %}{% endblock %} </a> </h1>
    <hr>
    <p><a href="{% url 'taskmanager:index' %}" > Home </a> </p>
    <h2>
      {% if user.is_authenticated %}
        <p>Hello, {{ user.get_username }}! </p>
      {% else %}
        <p>Hello, Guest!</p>
      {% endif %}
    {% block title %} {% endblock %}
    </h2>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>
    {% else %}
    {% block content %} {% endblock %}
    {% endif %}
      <p>
        {% if user.is_authenticated %}
        <br>  <a href="{% url 'taskmanager:logout' %}" > Logout </a>
        {% endif %}
      </p>
    </body>
</html>

taskmanager/templates/taskmanager/create_task.html
{% extends "taskmanager/base.html" %}
{% block appname %} Task Manager {% endblock %}
{% block title %} Create Task {% endblock %}
{% block content %}
<form action="{% url 'taskmanager:create' %}" method="POST">
    {% csrf_token %}
    {{ taskform.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

taskmanager/templates/taskmanager/delete.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p>Deleted successfully!</p>

taskmanager/templates/taskmanager/detail.html
{% extends "taskmanager/base.html" %}
{% block appname %} Task Manager {% endblock %}
{% block title %} Task Details {% endblock %}

{% block content %}
<form action="{% url 'taskmanager:toggle_status' task.id %}" method="post">
{% csrf_token %}
{% if task.status %}
  <input type="submit" value=" Mark as ToDo ">
{% else %}
  <input type="submit" value=" Mark Complete ">
{% endif %}
</form>
<p> <b>Title</b> : {{ task.task_title }}</p>
<p> <b>Description</b> : {{ task.description }} </p>
<p> <b>Created</b> : {{ task.created }} </p>
<p> <b>Modified</b> : {{ task.modified }} </p>
{% if task.status %}
<p> <b>Finished</b> : {{ task.finished }} </p>
{% else %}
<form action="{% url 'taskmanager:edit' task.id %}" method="get">
{% csrf_token %}
  <input type="submit" value="Edit">
</form>
{% endif %}
<br>
<form action="{% url 'taskmanager:delete' task.id %}" method="post">
{% csrf_token %}
  <input type="submit" value="Delete">
</form>
{% endblock %}

taskmanager/templates/taskmanager/edit_task.html
{% extends "taskmanager/base.html" %}
{% block appname %} Task Manager {% endblock %}
{% block title %} Edit task {% endblock %}

{% block content %}
<form action="{% url 'taskmanager:edit' task.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
{% endblock %}

taskmanager/templates/taskmanager/index.html
{% extends "taskmanager/base.html" %}
{% block appname %} Task Manager {% endblock %}
{% block title %} Task List {% endblock %}
{% block content%}
{% if latest_task_list %}
    <ul>
    {% for task in latest_task_list %}
        <li><a href="{% url 'taskmanager:detail' task.id %}">{{ task.task_title }}</a></li>
    {% endfor %}
    <br>
    </ul>
  <a href="{% url 'taskmanager:create' %}"> Create more</a>
{% else %}
    <p>All tasks done!</p>
    <li><a href="{% url 'taskmanager:create' %}"> Create new</a></li>
{% endif %}
<p><a href="{% url 'taskmanager:completed_tasks' %}"> View Completed Tasks </a></p>
{%endblock %}

taskmanager/templates/taskmanager/login.html
{% extends "taskmanager/base.html" %}
{% block appname %} Task Manager {% endblock %}
{% block title %}Login{% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
  <br>
  <p>Not Registered?
  <a href="{% url 'taskmanager:register' %}"> Sign Up! </a>
  </p>
{% endblock %}

taskmanager/templates/taskmanager/register.html
{% extends "taskmanager/base.html" %}
{% block appname %} Task Manager {% endblock %}
{% block title %}Register{% endblock %}

{% block content %}
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
  </form>
  <br>
  <p>Already Registered?
  <a href="{% url 'taskmanager:login' %}"> Login </a>
  </p>
{% endblock %}

taskmanager/templates/taskmanager/task_list.html
{% extends "taskmanager/base.html" %}
{% block appname %} Task Manager {% endblock %}
{% block title %} Completed Task List {% endblock %}
{% block content%}
{% if task_list %}
    <ul>
    {% for task in task_list %}
        <li><a href="{% url 'taskmanager:detail' task.id %}">{{ task.task_title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tasks done, lets do some work!</p>
    <a href="{% url 'taskmanager:index' %}"> View Todo </a>
{% endif %}
{%endblock %}